# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-11 11:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(default='135300100', max_length=32)),
                ('name', models.CharField(default='LiHua', max_length=32)),
            ],
        ),
    ]
