# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-13 06:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Management', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LessonOne',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(default='135300100', max_length=32)),
                ('level1', models.CharField(default='80', max_length=10)),
                ('level2', models.CharField(default='80', max_length=10)),
                ('level3', models.CharField(default='80', max_length=10)),
                ('level4', models.CharField(default='80', max_length=10)),
                ('level5', models.CharField(default='80', max_length=10)),
                ('train_time', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='person',
            name='age',
            field=models.CharField(default='25', max_length=3),
        ),
        migrations.AddField(
            model_name='person',
            name='gender',
            field=models.CharField(default='F', max_length=2),
        ),
        migrations.AlterField(
            model_name='person',
            name='number',
            field=models.CharField(default='1700001', max_length=32),
        ),
    ]
