# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-13 06:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Management', '0002_auto_20170513_0601'),
    ]

    operations = [
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lesson1', models.CharField(default='80', max_length=10)),
                ('lesson2', models.CharField(default='60', max_length=10)),
                ('lesson3', models.CharField(default='60', max_length=10)),
                ('average', models.CharField(default='60', max_length=10)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='person_grade', to='Management.Person')),
            ],
        ),
    ]
