# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-13 07:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Management', '0003_grade'),
    ]

    operations = [
        migrations.AddField(
            model_name='lessonone',
            name='average',
            field=models.CharField(default='60', max_length=10),
        ),
    ]
