# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-13 08:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Management', '0004_lessonone_average'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grade',
            name='person',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='person_grade', to='Management.Person'),
        ),
    ]
