# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-15 03:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Management', '0006_auto_20170513_1042'),
    ]

    operations = [
        migrations.CreateModel(
            name='Avtar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='static/avatar')),
            ],
        ),
        migrations.RemoveField(
            model_name='person',
            name='id',
        ),
        migrations.AddField(
            model_name='person',
            name='idcard',
            field=models.CharField(default='13027472347324', max_length=32),
        ),
        migrations.AddField(
            model_name='person',
            name='province',
            field=models.CharField(default='Shanghai', max_length=32),
        ),
        migrations.AlterField(
            model_name='person',
            name='age',
            field=models.CharField(default='25', max_length=32),
        ),
        migrations.AlterField(
            model_name='person',
            name='email',
            field=models.CharField(default='bigplane@qq.com', max_length=32),
        ),
        migrations.AlterField(
            model_name='person',
            name='number',
            field=models.CharField(default='1700001', max_length=32, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='person',
            name='phone',
            field=models.CharField(default='18510309110', max_length=32),
        ),
    ]
