# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-15 03:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Management', '0007_auto_20170515_0308'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='avatar',
            field=models.CharField(default='/static/avatar/timg.jpg', max_length=128),
        ),
    ]
