# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-15 04:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Management', '0009_auto_20170515_0413'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Avtar',
        ),
        migrations.AddField(
            model_name='person',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='avatar'),
        ),
    ]
