# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-15 04:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Management', '0010_auto_20170515_0424'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='avatar',
        ),
    ]
