# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-15 04:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Management', '0012_avatar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='avatar',
            name='id',
        ),
        migrations.AddField(
            model_name='avatar',
            name='number',
            field=models.CharField(default='1700001', max_length=32, primary_key=True, serialize=False),
        ),
    ]
