# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-15 07:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Management', '0013_auto_20170515_0454'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='age',
            field=models.CharField(default='25', max_length=3),
        ),
        migrations.AlterField(
            model_name='person',
            name='image',
            field=models.ImageField(blank=True, default='/avtar/timg.jpg', null=True, upload_to='avatar'),
        ),
        migrations.AlterField(
            model_name='person',
            name='phone',
            field=models.CharField(default='18510309110', max_length=15),
        ),
    ]
