# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-15 07:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Management', '0015_auto_20170515_0753'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='image',
            field=models.ImageField(default='settings.MEDIA_ROOT/avatar/timg.jpg', upload_to='avatar'),
        ),
    ]
