# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-16 06:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Management', '0018_auto_20170515_0811'),
    ]

    operations = [
        migrations.CreateModel(
            name='SuperUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='admin', max_length=32)),
                ('password', models.CharField(default='admin', max_length=32)),
            ],
        ),
        migrations.DeleteModel(
            name='Avatar',
        ),
        migrations.AlterField(
            model_name='lessonone',
            name='number',
            field=models.CharField(default='1700001', max_length=32),
        ),
    ]
