# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-16 07:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Management', '0019_auto_20170516_0603'),
    ]

    operations = [
        migrations.RenameField(
            model_name='superuser',
            old_name='name',
            new_name='username',
        ),
    ]
