# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-16 10:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Management', '0020_auto_20170516_0710'),
    ]

    operations = [
        migrations.CreateModel(
            name='LessonThree',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(default='1700001', max_length=32)),
                ('level1', models.DecimalField(decimal_places=2, default=80.0, max_digits=5)),
                ('level2', models.DecimalField(decimal_places=2, default=80.0, max_digits=5)),
                ('level3', models.DecimalField(decimal_places=2, default=80.0, max_digits=5)),
                ('level4', models.DecimalField(decimal_places=2, default=80.0, max_digits=5)),
                ('level5', models.DecimalField(decimal_places=2, default=80.0, max_digits=5)),
                ('level6', models.DecimalField(decimal_places=2, default=80.0, max_digits=5)),
                ('average', models.DecimalField(decimal_places=2, default=80.0, max_digits=5)),
                ('train_time', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='LessonTwo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(default='1700001', max_length=32)),
                ('level1', models.DecimalField(decimal_places=2, default=70.0, max_digits=5)),
                ('level2', models.DecimalField(decimal_places=2, default=70.0, max_digits=5)),
                ('level3', models.DecimalField(decimal_places=2, default=70.0, max_digits=5)),
                ('average', models.DecimalField(decimal_places=2, default=70.0, max_digits=5)),
                ('train_time', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterField(
            model_name='person',
            name='gender',
            field=models.CharField(default='F', max_length=2),
        ),
    ]
